services:
  dev:
    build: .
    # ports:
    #   - "2222:22"
    volumes:
      - home:/home
      - vscode-server:/root/.vscode-server
    restart: unless-stopped
    privileged: true
    labels:
      sshpiper.username: "${SSH_PROXY_USERNAME}"
      sshpiper.container_username: "dev"
      sshpiper.port: "22"

volumes:
  home:
  vscode-server:
